In [1]:
import pandas as pd
import numpy as np

In [2]:
apps_df=pd.read_csv("D:\\Data Engineer\\Project Pandas\\google-play-store.csv")

In [3]:
apps_df.head()

,app_id,title,reviews,ratings,min_installs,score,offers_iap,ad_supported,released,ratings_per_day,genre,genre_id,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
0,com.prettyteengames.royal.princess.wedding.mak...,Royal Princess Wedding Makeover and Dress Up,375.0,1023.0,100000,4.179863,True,True,2017-12-20,3,Casual,GAME_CASUAL,0.0,115,31,98,90,689
1,com.MayGreenStudio.dressup,Momo's Dressup,13492.0,25974.0,1000000,4.711096,False,True,2017-03-07,42,Casual,GAME_CASUAL,0.0,673,213,806,2561,21721
2,air.theflash.f2game.PrettyGirl23,Princess Pretty Girl,1974.0,4610.0,500000,4.295445,False,True,2015-01-18,3,Casual,GAME_CASUAL,0.0,382,206,287,528,3207
3,air.com.dressupone.animeschooluniforms,Anime School Uniforms,2586.0,6081.0,500000,4.209505,False,True,2013-08-20,3,Casual,GAME_CASUAL,0.0,628,193,524,668,4068
4,air.theflash.f2game.PrettyGirl7,Wedding Pretty girl,1409.0,3728.0,500000,4.195011,False,True,2014-09-01,2,Casual,GAME_CASUAL,0.0,358,185,300,414,2471

In [5]:
apps_df.describe()

,reviews,ratings,min_installs,score,ratings_per_day,price,rating_one_star,rating_two_star,rating_three_star,rating_four_star,rating_five_star
count,6.268300e+04,6.268300e+04,6.269400e+04,62683.000000,62694.000000,62694.000000,6.269400e+04,6.269400e+04,6.269400e+04,6.269400e+04,6.269400e+04
mean,1.529843e+04,4.936328e+04,2.035663e+06,4.221624,38.620506,0.414998,3.078124e+03,1.211618e+03,3.094328e+03,7.227599e+03,3.474295e+04
std,2.261505e+05,7.690255e+05,2.386872e+07,0.815517,430.422770,3.793236,6.050231e+04,2.193403e+04,5.230251e+04,1.117066e+05,5.368042e+05
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.600000e+01,4.100000e+01,1.000000e+03,4.100497,0.000000,0.000000,2.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,2.800000e+01
50%,1.440000e+02,3.980000e+02,5.000000e+04,4.403101,0.000000,0.000000,2.400000e+01,9.000000e+00,2.300000e+01,4.700000e+01,2.640000e+02
75%,1.500000e+03,4.488000e+03,5.000000e+05,4.637007,6.000000,0.000000,3.070000e+02,1.090000e+02,2.840000e+02,6.090000e+02,2.933000e+03
max,2.205377e+07,8.128486e+07,1.000000e+09,5.000000,40526.000000,369.990000,9.658715e+06,3.368101e+06,7.164984e+06,1.222342e+07,5.295266e+07

In [6]:
apps_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62694 entries, 0 to 62693
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   app_id             62694 non-null  object
 1   title              62694 non-null  object
 2   reviews            62683 non-null  float64
 3   ratings            62683 non-null  float64
 4   min_installs       62694 non-null  int64
 5   score              62683 non-null  float64
 6   offers_iap         62694 non-null  bool
 7   ad_supported       62694 non-null  bool
 8   released           61848 non-null  object
 9   ratings_per_day    62694 non-null  int64
 10  genre              62693 non-null  object
 11  genre_id           62693 non-null  object
 12  price              62694 non-null  float64
 13  rating_one_star    62694 non-null  int64
 14  rating_two_star    62694 non-null  int64
 15  rating_three_star  62694 non-null  int64
 16  rating_four_star   62694 non-null  int64
 17  rating_five_star   62694 non-null  int64
dtypes: bool(2), float64(4), int64(7), object(5)
memory usage: 7.8+ MB

In [9]:
apps_df.duplicated().sum()

np.int64(0)

In [7]:
apps_df.isna().sum()

app_id                 0
title                  0
reviews               11
ratings               11
min_installs           0
score                 11
offers_iap             0
ad_supported           0
released             846
ratings_per_day        0
genre                  1
genre_id               1
price                  0
rating_one_star        0
rating_two_star        0
rating_three_star      0
rating_four_star       0
rating_five_star       0
dtype: int64

In [8]:
apps_df.dropna(inplace = True)

In [10]:
apps_df["per_day"]= apps_df["min_installs"]/365
per_day=apps_df["per_day"]  
per_day.head()

0     273.972603
1    2739.726027
2    1369.863014
3    1369.863014
4    1369.863014
Name: per_day, dtype: float64

In [11]:
#What categories of applications get a lot of downloads per day?
max_download=apps_df.groupby("genre")["per_day"].sum().sort_values(ascending=False)
max_download.head(1)

genre
Tools    46491837.6
Name: per_day, dtype: float64

In [12]:
#2.What categories of applications don't get many downloads per day?
min_download=apps_df.groupby("genre")["per_day"].sum().sort_values(ascending=True)
min_download.head(1)

genre
Events    12521.835616
Name: per_day, dtype: float64

In [13]:
#3.What categories of applications get a lot of downloads per day?
max_app_download=apps_df.groupby("genre")["min_installs"].sum().sort_values(ascending=False)
max_app_download.head(1)

genre
Tools    16969520724
Name: min_installs, dtype: int64

In [18]:
#6.Calculate the average rating for each genre
ave_rate=apps_df.groupby("genre")["ratings"].mean().sort_values(ascending=False)
ave_rate

genre
Strategy                   319838.292627
Communication              257406.266556
Racing                     214782.702602
Action                     199709.507886
Social                     196183.723096
Arcade                     170599.173469
Casual                     153237.535632
Video Players & Editors    122835.460055
Word                        99129.206186
Role Playing                91775.921700
Adventure                   84403.164683
Sports                      79601.481902
Photography                 79363.746667
Trivia                      71271.406250
Weather                     67419.542735
Casino                      66806.870416
Puzzle                      60140.754932
Shopping                    58454.924242
Tools                       52044.811420
Simulation                  50558.912826
Music                       45085.365741
Board                       40506.361065
Card                        39213.570983
Productivity                34450.585778
Music & Audio               31052.821974
Personalization             27668.923722
Dating                      27491.047945
Entertainment               24796.085961
Maps & Navigation           22931.724571
News & Magazines            22896.236123
Libraries & Demo            21051.705128
Travel & Local              20608.783358
Comics                      19472.311377
Health & Fitness            12237.009471
House & Home                11067.641026
Finance                     10678.852255
Educational                  9688.838156
Lifestyle                    8958.141257
Parenting                    8803.779904
Books & Reference            7695.673964
Food & Drink                 6517.036993
Art & Design                 5955.644231
Business                     5362.647256
Education                    4593.544550
Auto & Vehicles              3454.953901
Beauty                       3330.245902
Medical                      1788.271689
Events                        899.048193
Name: ratings, dtype: float64

In [19]:
#7.Find the top 5 apps with the highest number of reviews.
top_app=apps_df.groupby("title")["reviews"].sum().sort_values(ascending=False)
top_app.head(5)

title
Instagram                                   21702496.0
WhatsApp Messenger                          19031005.0
Clash of Clans                              17895834.0
Messenger – Text and Video Chat for Free    15404150.0
Clean Master- Space Cleaner & Antivirus     11064681.0
Name: reviews, dtype: float64

In [20]:
#8.Count the number of apps that offer in-app purchases (IAP).
iap_count = apps_df['offers_iap'].sum()
iap_count

np.int64(13428)

In [21]:
#9. Determine the total number of installs for each genre.
total_number_installs=apps_df.groupby("genre")["min_installs"].sum().sort_values(ascending=False)
total_number_installs

genre
Tools                      16969520724
Communication              12122989700
Productivity               10147992740
Casual                      6224620360
Photography                 5811063981
Arcade                      5546004090
Action                      5111844100
Video Players & Editors     4723136910
Entertainment               4720979671
Social                      4269971910
Racing                      4089202110
Music & Audio               3949154360
Puzzle                      3367157950
Simulation                  3104353710
Personalization             2735750325
News & Magazines            2702117676
Sports                      2635304830
Travel & Local              2369601680
Books & Reference           2010847930
Health & Fitness            1649054720
Shopping                    1643799880
Strategy                    1434224000
Lifestyle                   1197538890
Education                   1152546755
Educational                  984407731
Adventure                    971091610
Business                     949933280
Board                        930568100
Finance                      831114910
Role Playing                 802934525
Maps & Navigation            776612430
Card                         740485950
Casino                       567465500
Music                        554587955
Word                         548160000
Weather                      493918500
Trivia                       380906650
Art & Design                 276816260
House & Home                 250684570
Food & Drink                 201916491
Dating                       168857510
Auto & Vehicles              117962510
Medical                      102764761
Comics                        90437060
Libraries & Demo              61944950
Parenting                     53942700
Beauty                        33960670
Events                         4570470
Name: min_installs, dtype: int64

In [22]:
apps_df['released'] = pd.to_datetime(apps_df['released'], errors='coerce')
print(apps_df.dtypes)

app_id                       object
title                        object
reviews                     float64
ratings                     float64
min_installs                  int64
score                       float64
offers_iap                     bool
ad_supported                   bool
released             datetime64[ns]
ratings_per_day               int64
genre                        object
genre_id                     object
price                       float64
rating_one_star               int64
rating_two_star               int64
rating_three_star             int64
rating_four_star              int64
rating_five_star              int64
per_day                     float64
dtype: object

In [23]:
#10. Find the earliest and latest release date in the dataset.
released_date = apps_df.sort_values(by='released', ascending=False)
far_date = released_date['released'].iloc[1]
near_date = released_date['released'].iloc[-1]
print(f"The near released date is {near_date},and The far released date is {far_date}")

The near released date is 2010-01-28 00:00:00,and The far released date is 2018-11-09 00:00:00

In [24]:
#11. Calculate the average number of ratings per day for apps with more than 10,000 reviews.
apps_df["reviews_per_day"]= apps_df["reviews"]/365
average_number_reviews=apps_df.groupby("title")["reviews_per_day"].sum().sort_values(ascending=False)
print(average_number_reviews[average_number_reviews>10000])

title
Instagram                                             59458.893151
WhatsApp Messenger                                    52139.739726
Clash of Clans                                        49029.682192
Messenger – Text and Video Chat for Free              42203.150685
Clean Master- Space Cleaner & Antivirus               30314.194521
Clash Royale                                          28624.443836
YouTube                                               25027.978082
Subway Surfers                                        24492.194521
Security Master - Antivirus, VPN, AppLock, Booster    19204.876712
Candy Crush Saga                                      17704.060274
Snapchat                                              17047.271233
UC Browser - Fast Download Private & Secure           15285.189041
Garena Free Fire                                      14508.073973
8 Ball Pool                                           13399.145205
Dream League Soccer 2018                              12937.265753
My Talking Tom                                        12704.558904
360 Security - Free Antivirus, Booster, Cleaner       12474.849315
Mobile Legends: Bang Bang                             11930.739726
Pokémon GO                                            11786.923288
BBM - Free Calls & Messages                           11246.317808
My Talking Angela                                     11023.153425
VivaVideo - Video Editor & Photo Movie                10731.438356
Spotify Music                                         10502.416438
Shadow Fight 2                                        10429.106849
Name: reviews_per_day, dtype: float64

In [25]:
#12. Identify the top 3 genres with the highest average app score.
apps_df["ave_score"]=apps_df["score"].mean()
apps_df.groupby("genre")["ave_score"].sum().sort_values(ascending=False).head(3)

genre
Education        28067.913594
Tools            25715.168236
Entertainment    14226.492613
Name: ave_score, dtype: float64

In [ ]:
#13. Determine the percentage of apps that are ad-supported and offer in-app purchases 
total_apps = len(apps_df)
count_both = ((apps_df["offers_iap"] == True) & (apps_df["ad_supported"] == True)).sum()
percentage = (count_both / total_apps) * 100
print("percentage is:",percentage,"%")

percentage is: 17.01133442204149 %

In [27]:
#14. Find the most common release year for apps in the dataset.
most_common_year = apps_df['released'].dt.year.value_counts().idxmax()
most_common_year

np.int32(2018)

In [28]:
#15. Calculate the correlation between the number of reviews and the average rating for each genre.
correlation = apps_df.groupby("genre")[["reviews", "score"]].corr()
print(correlation)

                                  reviews     score
genre
Action                  reviews  1.000000  0.131182
                        score    0.131182  1.000000
Adventure               reviews  1.000000 -0.004351
                        score   -0.004351  1.000000
Arcade                  reviews  1.000000  0.050393
...                                   ...       ...
Video Players & Editors score    0.052647  1.000000
Weather                 reviews  1.000000  0.090615
                        score    0.090615  1.000000
Word                    reviews  1.000000 -0.069218
                        score   -0.069218  1.000000

[96 rows x 2 columns]

In [ ]:
#16. Calculate the weighted average rating for each genre, where the weight is the number of reviews. 
def weighted_avg(group):
    return (group["score"] * group["reviews"]).sum() / group["reviews"].sum()
weighted = apps_df.groupby("genre").apply(
    weighted_avg, include_groups=False
).reset_index()
weighted.columns = ["genre", "weighted_avg_rating"]
weighted["weighted_avg_rating"] = weighted["weighted_avg_rating"].round(2)
weighted = weighted.sort_values("weighted_avg_rating", ascending=False)
print(weighted)

                      genre  weighted_avg_rating
30                Parenting                 4.61
15                Education                 4.58
41                 Strategy                 4.52
7         Books & Reference                 4.51
21         Health & Fitness                 4.50
47                     Word                 4.50
10                   Casino                 4.50
42                    Tools                 4.49
31          Personalization                 4.48
6                     Board                 4.48
2                    Arcade                 4.46
44                   Trivia                 4.46
26                  Medical                 4.45
9                      Card                 4.45
36             Role Playing                 4.45
40                   Sports                 4.45
34                   Puzzle                 4.45
35                   Racing                 4.45
46                  Weather                 4.44
3              Art & Design                 4.44
32              Photography                 4.44
5                    Beauty                 4.43
0                    Action                 4.43
24                Lifestyle                 4.42
33             Productivity                 4.42
37                 Shopping                 4.42
38               Simulation                 4.41
45  Video Players & Editors                 4.41
11                   Casual                 4.41
12                   Comics                 4.41
28            Music & Audio                 4.40
18                   Events                 4.40
4           Auto & Vehicles                 4.36
39                   Social                 4.36
43           Travel & Local                 4.36
20             Food & Drink                 4.34
27                    Music                 4.34
19                  Finance                 4.32
17            Entertainment                 4.32
29         News & Magazines                 4.32
23         Libraries & Demo                 4.31
13            Communication                 4.31
8                  Business                 4.31
1                 Adventure                 4.29
16              Educational                 4.28
25        Maps & Navigation                 4.27
22             House & Home                 4.18
14                   Dating                 4.17

In [30]:
#17. Identify the app with the highest ratio of ratings per review for each genr
apps_df['rating_review_ratio'] = apps_df['ratings'] / apps_df['reviews']

best_ratio_apps = apps_df.loc[
    apps_df.groupby('genre')['rating_review_ratio'].idxmax()
][['genre', 'title', 'rating_review_ratio']]

best_ratio_apps.head()

,genre,title,rating_review_ratio
60418,Action,Wilderness Hunter 2016,inf
62329,Adventure,The Adventure Coin and Theft,26.5
47995,Arcade,Retro GEN Pro - MD Emulator,inf
30627,Art & Design,Graffiti Alphabet Letters Drawing Ideas,inf
223,Auto & Vehicles,SphereDR,inf